### PR TITLE
Update Finance.md

### PR DESCRIPTION
**Pull request by serkor1**
Hi,

I have added `cryptoQuotes`-package, which I am the author and maintainer of, to the main file.  The package can be found on [Github](https://github.com/serkor1/cryptoQuotes) and [CRAN](https://cran.r-project.org/web/packages/cryptoQuotes/index.html)

Best,

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks. I hope it sticks around, there is quite some volatility in these coin packages :wink:

**Comment by serkor1** [comment]
"This project is different" 😂 - the plan is to keep it around if all goes well, thank you, its an honor to be listed amongst giants!

**Comment by eddelbuettel** [comment]
I need to to do a little clean up in the task view file and move this and one or two more packages down to the 'data' section.  But small fries -- thanks for the PR.

**Comment by serkor1** [comment]
You are in charge - and in hindsight, the data section is probably more fitting too, as that os the main usecase for this particular library!

Best,

**Pull request merged**
